### ISSUE TITLE
Feature: use submodule for plugins

### ISSUE THREAD

**Issue by yuandong1222** [ketor/vimrc-old#1]
@ketor 
Can you list the plugin and their Repos?

**Comment by ketor** [comment]
bundle目录：
STL-Syntax
origin	https://github.com/Mizuchi/STL-Syntax (fetch)
ack.vim
origin	https://github.com/mileszs/ack.vim (fetch)
ag.vim
origin	https://github.com/rking/ag.vim (fetch)
csv.vim
origin	https://github.com/chrisbra/csv.vim (fetch)
jellybeans.vim
origin	https://github.com/nanotech/jellybeans.vim (fetch)
neocomplcache.vim
origin	https://github.com/Shougo/neocomplcache.vim (fetch)
neomru.vim
origin	https://github.com/Shougo/neomru.vim (fetch)
neosnippet-snippets
origin	https://github.com/Shougo/neosnippet-snippets (fetch)
neosnippet.vim
origin	https://github.com/Shougo/neosnippet.vim (fetch)
nerdcommenter
origin	https://github.com/scrooloose/nerdcommenter (fetch)
nerdtree
origin	https://github.com/scrooloose/nerdtree (fetch)
papercolor-theme
origin	https://github.com/NLKNguyen/papercolor-theme (fetch)
rainbow_parentheses.vim
origin	https://github.com/kien/rainbow_parentheses.vim (fetch)
tagbar
origin	https://github.com/majutsushi/tagbar (fetch)
tagbar-phpctags.vim
origin	https://github.com/vim-php/tagbar-phpctags.vim (fetch)
taghighlight
origin	https://github.com/abudden/taghighlight-automirror (fetch)
undotree
origin	https://github.com/mbbill/undotree (fetch)
unite.vim
origin	https://github.com/Shougo/unite.vim (fetch)
vim-airline
origin	https://github.com/bling/vim-airline (fetch)
vim-colors-solarized
origin	https://github.com/altercation/vim-colors-solarized (fetch)
vim-easymotion
origin	https://github.com/easymotion/vim-easymotion (fetch)
vim-fugitive
origin	https://github.com/tpope/vim-fugitive (fetch)
vim-go
origin	https://github.com/fatih/vim-go (fetch)
vim-indexed-search
origin	https://github.com/henrik/vim-indexed-search (fetch)
vim-signature
origin	https://github.com/kshenoy/vim-signature (fetch)
vim-togglemouse
origin	https://github.com/nvie/vim-togglemouse (fetch)
vim-togglenumber
origin	https://github.com/tkhoa2711/vim-togglenumber (fetch)
vimproc.vim
origin	https://github.com/Shougo/vimproc.vim.git (fetch)

**Comment by ketor** [comment]
.vim这个目录本身是一个repo：
origin	https://github.com/tpope/vim-pathogen (fetch)

**Comment by yuandong1222** [comment]
You prefer fork them to your repo or use their origin repo directly?

**Comment by ketor** [comment]
Use origin is prefered!  Some of the plugins is on developing.

**Comment by yuandong1222** [comment]
Got
